"""Errors generated by the library. 

If Aristoxenus is imported as part of another program, all errors generated
by Aristoxenus can be caught under the heading of the common parent error
```AristoxenusException```.
"""


class AristoxenusException(Exception):
    """Parent exception of all errors deliberately raised by the Aristoxenus 
    library."""


class AristoxenusValueError(AristoxenusException):
    """Error that indicates that the given value is faulty.

    This error is used in places where the value is not covered by a more
    specific error type.
    """


class AristoxenusIndexError(AristoxenusException):
    """Error that indicates that a sequence index does not exist.

    This error is used in places where the sequence is not an interval 
    sequence.
    """


class IntervalStructureError(AristoxenusException):
    """Error that indicates that the given interval structure is incompatible
    in context.

    This error is used in places where the bitcount or bitlength of an 
    interval structure is incorrect.
    """


class NoteNameError(AristoxenusException):
    ''' 
    Error indicating that an unrecognized note name was passed.
    '''


class HeptatonicScaleError(AristoxenusException):
    '''
    Error indicating that a scale does not conform to the heptatonic scale 
    pattern or nomenclature.
    '''


class ChordNameError(AristoxenusException):
    '''
    Error indicating that the alphabetical note name in a chord is not one of 
    the note names in the list returned from `nomenclature.legal_chord_names`.
    '''


class ChordSymbolError(AristoxenusException):
    ''' 
    Error indicating that one or more of the suffixes of a chord symbol are 
    incompatible with the parser.
    '''


class UnknownKeywordError(AristoxenusException):
    ''' 
    Error indicating that the passed keyword was not recognized in context.    
    '''


class UnfinishedFunctionError(Exception):
    """Error that reminds the programmer that a particular bit of logic hasn't
    been written completely.
    """
