
class AristoxenusException(Exception):
    """Parent exception of all errors generated by the Aristoxenus library."""


class AristoxenusValueError(AristoxenusException):
    """Error that indicates that the given value is faulty, for a value not
    covered by the other error types.
    """

class AristoxenusIndexError(AristoxenusException):
    """Error that indicates that a sequence index does not exist."""

class IntervalStructureError(AristoxenusException):
    """Error that indicates that the given interval structure is incompatible
    in context.
    """

class IntervalOutOfBoundsError(AristoxenusException):
    """
    Error that indicates that the given interval exceeded the expected range.
    """

class NoteNameError(AristoxenusException):
    ''' 
    Error indicating that an unrecognized note name was passed.
    '''


class HeptatonicScaleError(AristoxenusException):
    '''
    Error indicating that a scale does not conform to the heptatonic scale 
    pattern or nomenclature.
    '''


class ChordNameError(AristoxenusException):
    '''
    Error indicating that the alphabetical note name in a chord is not one of 
    the note names in the list returned from `nomenclature.legal_chord_names`.
    '''


class ChordSymbolError(AristoxenusException):
    ''' 
    Error indicating that one or more of the suffixes of a chord symbol are 
    incompatible with the parser.
    '''
    

class UnknownKeywordError(AristoxenusException):
    ''' 
    Error indicating that the passed keyword was not recognized in context.    
    '''