'''
Functions pertaining to making musical diagrams (aside from staff notation).
'''

import dataclasses

from src import nomenclature, utils
from data import (chord_symbols,
                  constants,
                  keywords)

from data.types import GuitarFretboard
from data.instrument_config import GUITAR_STANDARD_TUNING


def guitar_fretboard(strings: int = 6,
                     tuning: list[str] | tuple[str, ...] = GUITAR_STANDARD_TUNING,
                     frets: int = 22,
                     format_: str = keywords.SCIENTIFIC
                     ) -> GuitarFretboard:
    '''
    Return a nested tuple representing a given number of strings and a given 
    tuning.

    Parameters
    ----------
    strings : int   
        The number of strings the guitar will have.
    tuning : str or list of strings
        The notes that each open string will be tuned to. The number of notes
        must be the same as the number of strings.

    Returns
    -------
    tuple of tuple of str
        A table representing the notes on the strings of a guitar in the 
        given formatting.

    Notes
    -----
    A tuning in scientific notation will be converted to plain, but a tuning
    in plain cannot be converted to scientific.
    '''
    diagram: list[tuple[str, ...]] = []
    frets += 1
    if format_ == keywords.SCIENTIFIC:
        all_notes = nomenclature.scientific_range()
        tuning = list(map(nomenclature.decode_scientific_enharmonic, tuning))

    elif format_ == keywords.PLAIN:
        all_notes = nomenclature.chromatic() * constants.TONES
        tuning = list(map(nomenclature.decode_enharmonic, tuning))

    else:
        raise ValueError(format_)

    for string in range(strings):
        starting_note = all_notes.index(tuning[string])
        ending_note = starting_note + frets
        string_notes = all_notes[starting_note: ending_note]
        diagram.append(tuple(string_notes))

    diagram.reverse()
    return tuple(diagram)


def simplify_guitar_fretboard(diagram: GuitarFretboard) -> GuitarFretboard:
    '''
    Make sure a guitar fretboard diagram is using plain binomial notation
    and not scientific notation.

    Parameters
    ----------
    diagram : GuitarFretboard
        A guitar fretboard in scientific notation.

    Returns
    -------
    GuitarFretboard
        A guitar fretboard in plain binomial notation.
    '''

    new_diagram: list[tuple[str, ...]] = []
    for string in diagram:
        new_diagram.append(tuple(map(nomenclature.decode_enharmonic, string)))
    return tuple(new_diagram)



def filter_guitar_fretboard(guitar_tuning: GuitarFretboard,
                            note_list: tuple[str, ...] | list[str]
                            ) -> GuitarFretboard:
    '''
    Filter a given guitar fretboard diagram so that it only displays the given
    notes and the '-' symbol.

    Parameters
    ----------
    guitar_tuning : tuple of tuple of str
        A guitar tuning in conformity to the type of diagram  
        generated by `digrams.guitar_tuning`, or a sub-position
        of same
    note_list : tuple or list of str
        Notes that will be retained in the new diagram.

    Returns
    -------
    tuple of tuple of str
        The same guitar fretboard diagram, but retaining only the given notes
        and replacing all others with '-'.
    '''
    diagram: list[tuple[str, ...]] = []
    new_string: list
    for string in guitar_tuning:
        new_string = []
        for note in string:
            if note in note_list:
                new_string.append(note)
            else:
                new_string.append('-')

        diagram.append(tuple(new_string))

    return tuple(diagram)


def get_positional_fingering(guitar_fingering: GuitarFretboard,
                             starting_column: int,
                             span: int
                             ) -> GuitarFretboard:
    '''
    Return a slice of the columns of a guitar fretboard, representing a 
    positional fingering.

    Parameters
    ----------
    guitar_fingering : GuitarFingering
        A fretboard diagram like that generated by `guitar_fretboard`
    starting_column : int
        The column of the index finger.
    span : int
        The number of frets to include in the fingering.

    Returns
    -------
    GuitarFingering
        _description_

    Notes
    -----
    Apply the fretboard filter AFTER getting the positional fingering.
    '''
    diagram: list[tuple[str, ...]] = []
    for string in guitar_fingering:
        diagram.append(tuple(note for index, note in enumerate(
            string) if index in range(starting_column, starting_column+span)))

    return tuple(diagram)



def convert_fretboard_to_relative(diagram: GuitarFretboard, 
                                  tonal_centre: str
                                  ) -> GuitarFretboard:
    '''
    Convert a fretboard diagram to use interval symbols instead of note names.

    Parameters
    ----------
    diagram : GuitarFretboard
        A fretboard diagram with note names.
    tonal_centre : str
        The note that will serve as the tonic/root

    Returns
    -------
    GuitarFretboard
        A new fretboard with the interval symbols relative to the given tonic
    '''

    diagram = simplify_guitar_fretboard(diagram)
    interval_symbols = [symbol for symbol in chord_symbols.interval_symbol_prescription.values()]
    chromatic_ = utils.shift_list(nomenclature.chromatic(), tonal_centre)
    conversion: dict[str, str] = dict(zip(chromatic_, interval_symbols))

    new_diagram: list[tuple[str, ...]] = []
    for string in diagram:
        new_string = []
        for note in string:
            new_string.append(conversion[note])
        new_diagram.append(tuple(new_string))

    return tuple(new_diagram)








@dataclasses.dataclass
class ChordSymbol:

    initial_symbol: str
    parsing_symbol: str = ''
    recognized_sub_symbols: list[str] = dataclasses.field(default_factory=list)
    unrecognized_sub_symbols: list[str] = dataclasses.field(
        default_factory=list)
    interval_structure: int = 1

    def __post_init__(self):
        self.parsing_symbol = self.initial_symbol

    def recognize(self, symbol):
        self.recognized_sub_symbols.append(symbol)
        self.parsing_symbol = self.parsing_symbol.replace(symbol, '')

    def ignore(self, symbol):
        self.unrecognized_sub_symbols.append(symbol)
        self.parsing_symbol = self.parsing_symbol.replace(symbol, '')

    def add(self, interval):
        self.interval_structure |= interval

    def subtract(self, interval):
        self.interval_structure ^= (interval - 1)
