from src.pitch_mapping import next_mode, previous_mode

class DoubleOctave():
    '''
    Representation of the double octave as a 24-bit integer.
    
    The double octave provides a structural paradigm for chords
    in which extensions in the upper octave are recognized as
    distinct from colour tones in the lower octave. This same
    paradigm can be applied to scales, so that the two octaves
    differ in their intervallic structure. 

    Schema:
        ========  ========  ======== 
        aaaaaaaa  aaaabbbb  bbbbbbbb  
        ========  ========  ======== 

        a = 12-bit upper octave
        b = 12-bit lower octave
    
    Reminder:
        The lowest pitch serves as the tonic/root, and occupies the
        least significant bit. The number of bits in the collection
        must remain fixed in order to ensure correct modal inversions.

    Bonus:
        Double octaves can be collapsed in order to determine what,
        if any, scale results from the union:
            maj13 (= 0b10001000100100010010001)
            >> 0b101010110101 (= major scale)
        
        Single octaves can extrapolate a chord voicing by transposing
        every x note into a new range:
            0b101010110101 (= major scale; tertial)
            >> 0b10001000100100010010001 (= maj13)
        Chord voicings generated by this method will terminate at the 
        limit of the double octave, and not all notes may be used:
            0b101010110101 (= major scale; quintal)
            >> 100000000010000010000001 = (Dmajquint)
    '''

    def __init__(self) -> None:

        self.__bits: int = 24
        self.collection: int = 0

    def __int__(self):
        return self.collection

    def __index__(self):
        return int(self)

    def __add__(self, interval: int) -> int:
        return self.collection | interval

    def __sub__(self, interval: int) -> int:
        return self.collection ^ interval

    def __iadd__(self, interval: int) -> 'DoubleOctave':
        self.collection |= interval
        return self

    def __isub__(self, interval: int) -> 'DoubleOctave':
        self.collection ^= interval
        return self

    def __str__(self):
        return f'Pitches: {self.collection} = {bin(self.collection)}'

    def __len__(self) -> int:
        return self.collection.bit_count()

    def bind_octaves(self, lower: int, higher: int) -> int:
        '''Take two 12-bit octaves and bind them into a 24-bit double octave.'''
        return (lower << int(self.__bits/2)) | higher

    @property
    def lower(self) -> int:
        '''Return the lower octave.'''
        return (self.collection >> int(self.__bits/2))

    @lower.setter
    def lower(self, lower: int) -> None:
        self.collection = self.bind_octaves(lower, self.higher)

    @property
    def higher(self) -> int:
        '''Return the upper octave.'''
        return self.collection & (2 ** int(self.__bits / 2) - 1)

    @higher.setter
    def higher(self, higher: int) -> None:
        self.collection = self.bind_octaves(self.lower, higher)

    def next_inversion(self) -> int:
        '''Rotate the pitch collection left to begin with the next flipped bit.'''
        return next_mode(self.collection, self.__bits)
    
    def previous_inversion(self) -> int:
        '''Rotate the pitch collection right to begin with the previous flipped bit.'''
        return previous_mode(self.collection, self.__bits)

